version: "3"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydatabase
    ports:
      - "5001:5000"
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  frontend2:
    build: ./frontend2
    ports:
      - "3001:3000"
    
      
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - frontend2

volumes:
  postgres-data:
